name: Novel_Solutions
services:
  web:
    image: novel_solutions:dev
    container_name: novel_solutions
    build:
      context: ./Novel_Solutions 
      dockerfile: Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: mysql://admin:admin@novel_solutions_db:3306/novel_solutions_db
    ports:
      - "8000:8000"
    depends_on:
      - novel_solutions_db

  novel_solutions_db:
    image: mysql:latest
    container_name: novel_solutions_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: novel_solutions_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    
   
    
  
