

name: Build - Test - Push 
on: 
  push: 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps: 

    - name: Checkout
      uses: actions/checkout@v4

    - run: ls -a