

name: Build - Test - Push 
on: 
  push: 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps: 

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup - BuildX
      uses: docker/setup-buildx-action@v3


    - name: Login - Docker
      uses: docker/login-action@v3 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    

    - name: Docker - Build / Push 
      uses: docker/build-push-action@v6
      with:
        file: ./Novel_Solutions/Dockerfile
        push: false
        tags: wip